# Run website:
# docker compose -f development.yml build --parallel && docker compose -f development.yml up -d --remove-orphans

# Run this the first time to create the dev files:
# docker compose -f development.yml --profile init run --rm frontend-init ; docker compose -f development.yml --profile init run --rm backend-init

# To create a backend feature's app: APP_NAME=changename docker compose --profile init -f development.yml run --rm app-init
# include/remove add-on on package.json: docker compose -f development.yml --profile init run --rm npm-init

volumes:
  db_data:

services:
  traefik:
    image: traefik:v3.5
    ports:
      - "80:80"
      - "8080:8080"   # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    command:
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--ping=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

  backend:
    env_file: .env
    build:
      context: .
      dockerfile: backend/_config/Dockerfile.development
    volumes:
      - ./backend:/app:delegated
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 1m
      timeout: 3s
      retries: 10
      start_period: 10s
    labels:
      - "traefik.enable=true"

      # Backend routes handled by Traefik
      - "traefik.http.routers.backend.rule=Host(`localhost`) && (PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/static`) || PathPrefix(`/media`))"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.priority=100"

      # Remove /api prefix ONLY for local backend
      - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=strip-api-prefix"

      # Backend port
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          memory: "256M"
    restart: on-failure

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword123
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-postgres}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always




# Initialization ------------------
  frontend-init:
    profiles: ["init"]
    image: node:20
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: >
      sh -c "
        npm install -g npm@latest &&
        if [ -f Dockerfile ]; then mv Dockerfile ../Dockerfile.backup; fi &&
        npx create-next-app@latest . &&
        if [ -f ../Dockerfile.backup ]; then mv ../Dockerfile.backup ./Dockerfile; fi &&
        npm install
      "

  npm-init:
    profiles: ["init"]
    image: node:18-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./backend/_config/requirements/npm.txt:/deps/npm.txt:ro
    command: >
      sh -c '
        apt-get update && apt-get install -y jq && rm -rf /var/lib/apt/lists/* &&
        echo "📦 Syncing npm dependencies with /deps/npm.txt..." &&

        wanted_deps=$(grep -v "^\s*#" /deps/npm.txt | sed "/^\s*$/d")

        for dep in $$wanted_deps; do
          if ! grep -q "\"$$dep\"" package.json; then
            echo "Installing $$dep..."
            npm install "$$dep" --save --legacy-peer-deps
          else
            echo "$$dep already present, skipping."
          fi
        done

        current_deps=$(jq -r ".dependencies | keys[]" package.json)
        for dep in $$current_deps; do
          if ! echo "$$wanted_deps" | grep -qx "$$dep"; then
            echo "Removing extra dependency $$dep..."
            npm uninstall "$$dep" --save
          fi
        done

        echo "✅ package.json now strictly matches /deps/npm.txt"
      '

  backend-init:
    profiles: ["init"]
    image: python:3.11-slim
    volumes:
      - ./backend:/app
    working_dir: /app
    command: >
      sh -c '
        apt-get update &&
        apt-get install -y sed &&
        pip install --upgrade pip &&
        pip install --upgrade django &&
        django-admin startproject _config . &&
        sed -i "s/from pathlib import Path/import os\\nfrom pathlib import Path/" _config/settings.py &&
        sed -i "s/^SECRET_KEY = .*/SECRET_KEY = os.getenv('\''DJANGO_SECRET_KEY'\'', '\''dev-secret-key-for-testing-only-not-for-production'\'')/" _config/settings.py &&
        sed -i "s/^DEBUG = .*/DEBUG = os.getenv('\''DEBUG'\'', '\''False'\'').lower() in ('\''true'\'', '\''1'\'', '\''yes'\'')/" _config/settings.py &&
        sed -i "/ALLOWED_HOSTS = \[\]/c\\hosts = os.getenv('\''HOSTS'\'', '\''localhost,127.0.0.1,0.0.0.0'\'')\\nALLOWED_HOSTS = [host.strip() for host in hosts.split('\'', '\'') if host.strip()]" _config/settings.py &&
        sed -i "/INSTALLED_APPS = \[/a\\    '\''corsheaders'\'',\\n    '\''rest_framework'\'',\\n    '\''rest_framework.authtoken'\'',\\n    '\''authentication'\'',\\n    '\''donations'\'',\\n    '\''medicine'\'',\\n    '\''beneficiary'\''," _config/settings.py &&
        sed -i "/MIDDLEWARE = \[/a\\    '\''whitenoise.middleware.WhiteNoiseMiddleware'\'',\\n    '\''corsheaders.middleware.CorsMiddleware'\'',\\n    '\''django.middleware.locale.LocaleMiddleware'\''," _config/settings.py &&
        sed -i "s/^LANGUAGE_CODE = .*/LANGUAGE_CODE = '\''es-mx'\''/" _config/settings.py &&
        sed -i "/LANGUAGE_CODE = '\''es-mx'\''/a\\LANGUAGES = [\\n    ('\''en'\'', '\''English'\''),\\n    ('\''es'\'', '\''Spanish'\''),\\n]" _config/settings.py &&
        sed -i "/# Database/,+10d" _config/settings.py &&
        printf "\\n# Database\\nDATABASES = {\\n    'default': {\\n        'ENGINE': 'django.db.backends.postgresql',\\n        'NAME': os.getenv('"'"'DB_NAME'"'"'),\\n        'USER': os.getenv('"'"'DB_USER'"'"'),\\n        'PASSWORD': os.getenv('"'"'DB_PASSWORD'"'"'),\\n        'HOST': os.getenv('"'"'DB_HOST'"'"'),\\n        'PORT': os.getenv('"'"'DB_PORT'"'"'),\\n    }\\n}\\n" >> _config/settings.py &&
        echo "\\nSTATIC_URL = '/static/'" >> _config/settings.py &&
        echo "STATIC_ROOT = os.path.join(BASE_DIR, '_config/staticfiles')" >> _config/settings.py &&
        echo "MEDIA_URL = '/media/'" >> _config/settings.py &&
        echo "MEDIA_ROOT = os.path.join(BASE_DIR, 'media')" >> _config/settings.py &&
        echo "STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'" >> _config/settings.py &&
        echo "CORS_ALLOW_CREDENTIALS = True" >> _config/settings.py &&
        echo "REST_FRAMEWORK = {\\n    'DEFAULT_AUTHENTICATION_CLASSES': [\\n        'rest_framework.authentication.TokenAuthentication',\\n        'rest_framework.authentication.SessionAuthentication',\\n    ],\\n}" >> _config/settings.py &&
        sed -i "$ a \
        if DEBUG:\
        \n    CORS_ALLOW_ALL_ORIGINS = True\
        \n    CORS_ALLOWED_ORIGINS = [\
        \n        'http://localhost:3000',\
        \n        'https://localhost:3000',\
        \n        'http://127.0.0.1:3000',\
        \n        'https://127.0.0.1:3000',\
        \n        'http://frontend:3000',\
        \n        'https://frontend:3000',\
        \n    ]\
        \n    CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS + [\
        \n        'http://localhost:8000',\
        \n        'https://localhost:8000',\
        \n        'http://localhost:80',\
        \n        'https://localhost:443',\
        \n        'http://backend:8000',\
        \n        'https://backend:8000',\
        \n        'http://localhost',\
        \n        'https://localhost',\
        \n    ]\
        \n    REST_FRAMEWORK['DEFAULT_PERMISSION_CLASSES'] = [\
        \n        'rest_framework.permissions.AllowAny',\
        \n    ]\
        else:\
        \n    CORS_ALLOWED_ORIGINS = [\
        \n        'https://yourproductiondomain.com',\
        \n    ]\
        \n    CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS\
        \n    REST_FRAMEWORK['DEFAULT_PERMISSION_CLASSES'] = [\
        \n        'rest_framework.permissions.IsAuthenticatedOrReadOnly',\
        \n    ]" _config/settings.py
      '

  app-init:
    profiles: ["init"]
    image: python:3.11-slim
    volumes:
      - ./backend:/app
    working_dir: /app
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y sed &&
      pip install --upgrade pip &&
      pip install django python-decouple djangorestframework django-cors-headers &&
      django-admin startapp ${APP_NAME}
      "
    environment:
      - APP_NAME=app
